services:
  submit:
    build:
      context: ./submit-service
    ports:
      - "3200:3200"  # Hardcoded, since ${PORT} from env_file is not available during Compose parsing
    depends_on:
      - submit-rabbitmq
    env_file:
      - ./submit-service/.env  # This will set variables inside the container
    environment:
      - RABBITMQ_URL
      - QUESTION_SERVICE_URL
    volumes:
      - ./submit-service:/app
      - submit-cache:/app/cache
    networks:
      - microservices-network

  submit-rabbitmq:
    image: rabbitmq:3-management
    container_name: submit-rabbitmq
    ports:
      - "4201:5672"
      - "4202:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network

volumes:
  submit-cache:

networks:
  microservices-network:
    driver: bridge
