services:
  moderate:
    build:
      context: ./moderate-service
    ports:
      - "3100:3100"  # Hardcoded to avoid dependency on external .env for host port
    env_file:
      - ./moderate-service/.env  # Load environment variables from file
    environment:
      - RABBITMQ_URL
      - MODERATE_RABBITMQ_URL
      - QUESTION_SERVICE_URL
    volumes:
      - ./moderate-service:/app
      - moderate-cache:/app/cache
    depends_on:
      - moderate-rabbitmq
    networks:
      - microservices-network

  moderate-rabbitmq:
    image: rabbitmq:3-management
    container_name: moderate-rabbitmq
    ports:
      - "4101:5672"     # AMQP port
      - "4102:15672"    # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network

volumes:
  moderate-cache:

networks:
  microservices-network:
    driver: bridge
