services:
  submit:
    build:
      context: ./submit-service
    ports:
      - "3200:3200"
    depends_on:
      - submit-rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@submit-rabbitmq:5672
      - QUESTION_SERVICE_URL=http://question:3000/categories
    volumes:
      - ./submit-service:/app
      - submit-cache:/app/cache
    networks:
      - microservices-network

  submit-rabbitmq:
    image: rabbitmq:3-management
    container_name: submit-rabbitmq
    ports:
      - "4201:5672"     # AMQP port for SUBMITTED_QUESTIONS
      - "4202:15672"    # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network

volumes:
  submit-cache:

networks:
  microservices-network:
    driver: bridge
