services:
  question:
    build:
      context: ./question-service
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - microservices-network
    environment:
      - DB_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=questiondb
    volumes:
      - ./question-service:/app

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: questiondb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  etl:
    build:
      context: ./etl-service
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=questiondb
      - RABBITMQ_URL=amqp://guest:guest@moderate-rabbitmq:5672
    networks:
      - microservices-network
    volumes:
      - ./etl-service:/app

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql_data:
