services:
  question:
    build:
      context: ./question-service
    ports:
      - "3000:3000"  # Hardcoded to keep host port explicit
    depends_on:
      - mongo
    env_file:
      - ./question-service/.env
    environment:
      - MONGO_URI
      - DB_TYPE=mongo
    volumes:
      - ./question-service:/app
    networks:
      - microservices-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-network

  etl:
    build:
      context: ./etl-service
    depends_on:
      - mongo
    env_file:
      - ./etl-service/.env
    environment:
      - MONGO_URI
      - RABBITMQ_URL
      - DB_TYPE=mongo
    volumes:
      - ./etl-service:/app
    networks:
      - microservices-network

volumes:
  mongo_data:

networks:
  microservices-network:
    driver: bridge
