services:
  question:
    build:
      context: ./question-service
    ports:
      - "3000:3000" # Hardcoded to keep host port explicit
    depends_on:
      - mysql
    env_file:
      - ./question-service/.env
    environment:
      - DB_TYPE=mysql
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./question-service:/app
    networks:
      - microservices-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: questiondb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  etl:
    build:
      context: ./etl-service
    depends_on:
      - mysql
    env_file:
      - ./etl-service/.env
    environment:
      - DB_TYPE=mysql
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - RABBITMQ_URL
    volumes:
      - ./etl-service:/app
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql_data:
