version: '3.8'

services:
  submit:
    build: .
    ports:
      - "3200:3200"
    environment:
      - MONGO_URI=mongodb://mongo:27017/questiondb  
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
