version: '3.8'

services:
  question:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - microservices-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/questiondb
    volumes:
      - .:/app

  mongo:
    image: mongo
    container_name: mongo  
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  mongo_data:
